# Book settings
title: "NeurodataReHack book"
author: "The tutorial authors"
copyright: "2022"

# Sphinx customizations
sphinx:
  config:
    # html_extra_path: ["assets"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Execution settings
execute:
  timeout: 3000
  exclude_patterns:
    - .github/*
  execute_notebooks: auto

only_build_toc_files: true

# HTML-specific settings
html:
  use_repository_button: true
  # use_issues_button: true
  use_edit_page_button: false
  home_page_in_navbar: true

# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"
  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  jupyterhub_url: "https://hub.dandiarchive.org"
  # The URL of the BinderHub (e.g., https://mybinder.org)
  binderhub_url: "https://mybinder.org"

repository:
  url: https://github.com/dandi/rehack-book
  path_to_book: docs
  branch: main

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
